[package]
name = "day-3"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
regex.workspace = true

[dev-dependencies]
divan.workspace = true

[[bench]]
name = "day-3"
path = "benches/benchmark.rs"
harness = false
